### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by JohannesKraggerud** [Halen84/ScriptHookRDR2DotNet-V2#3]
How can I install these files? Do I simply drag the INI, ASI, and DLL files into the main directory? The earlier version on NexusMods had a 'Scripts' folder, and some mods require you to put them into that folder. Can I create my own 'Scripts' folder, or how does this work? I apologize if these are obvious questions, but I am new to this.

**Comment by Halen84** [comment]
Basically, just extract everything from the [latest release](https://github.com/Halen84/ScriptHookRDR2DotNet-V2/releases/latest) .rar file into your RDR2 game directory for an easy installation.

You can create a "scripts" folder manually, lowercase.

**Comment by JohannesKraggerud** [comment]
> Basically, just extract everything from the [latest release](https://github.com/Halen84/ScriptHookRDR2DotNet-V2/releases/latest) .rar file into your RDR2 game directory for an easy installation.
> 
> You can create a "scripts" folder manually, lowercase.

Thanks
