### ISSUE TITLE
Script not loaded

### ISSUE THREAD

**Issue by Roms1383** [Halen84/ScriptHookRDR2DotNet-V2#7]
Hi and thanks for this tool, looks amazing !

I've tried installing as specified on readme like:
- [C++ ScriptHookRDR2 by Alexander Blade](http://www.dev-c.com/rdr2/scripthookrdr2/) : unzipped `dinput8.dll`, `ScriptHookRDR2.dll` in root game folder
- ScriptHookRDR2DotNet V2 :
   - unzipped `ScriptHookRDR2DotNet.dll`,`.asi`,`.ini` in root game folder
- created ` scripts` folder
   - built custom project with [RagdollExample.cs](https://github.com/Halen84/ScriptHookRDR2DotNet-V2/blob/master/examples/RagdollExample.cs) as `.dll`, renamed it as `.asi` and placed it in `scripts`
      > the only part that differs is that I changed the `namespace`

I launched the game, got the console displayed with `F8` as per `.ini` file,
but it seems the `.asi` I built from custom project does not get loaded at all.

I tried running `ListScripts()` in the console:

![console](https://github.com/Halen84/ScriptHookRDR2DotNet-V2/assets/21016014/b42a6f09-73fd-451d-8e2e-5aec26dcf422)

My guess here is that I probably messed up some configuration settings, maybe (I'm no stranger to programming but I'm a newcomer to C#).

Any help would be very much appreciated ! :)

**Comment by Halen84** [comment]
Do not renamed the compiled dll file, its supposed to be a dll.

**Comment by Roms1383** [comment]
Indeed it was that dead simple, now it works just like it's supposed to !
Sorry I got mislead from a (probably outdated / unrelated) comment on RDR forums, thanks a lot for helping out :)
